name: Core

on:
  workflow_dispatch:
    inputs:
      post_telegram:
        description: 'Post to Telegram'
        required: true
        type: boolean
  push:
    branches: [ npm-open ]
    tags: [ v* ]
  pull_request:
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
      CCACHE_BASEDIR: "${{ github.workspace }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: '5ec1cff/LSPosed'
          ref: '${{ github.ref }}'
          submodules: "recursive"
          fetch-depth: 0
      - run: |
          git tag --list v1.9.2 | grep -q -e . || git tag --create-reflog --no-edit v1.9.2 f8927757e8704d96611e1f3d75f702e3f0ce061f

      - name: Write key
        if: ${{ ( github.event_name != 'pull_request' && github.ref == 'refs/heads/npm-open' ) || github.ref_type == 'tag' }}
        run: |
          if [ ! -z "${{ secrets.KEY_STORE }}" ]; then
            echo androidStorePassword='${{ secrets.KEY_STORE_PASSWORD }}' >> gradle.properties
            echo androidKeyAlias='${{ secrets.ALIAS }}' >> gradle.properties
            echo androidKeyPassword='${{ secrets.KEY_PASSWORD }}' >> gradle.properties
            echo androidStoreFile='key.jks' >> gradle.properties
            echo ${{ secrets.KEY_STORE }} | base64 --decode > key.jks
          fi

      - name: Checkout libxposed/api
        uses: actions/checkout@v4
        with:
          repository: libxposed/api
          ref: '54582730315ba4a3d7cfaf9baf9d23c419e07006'
          path: libxposed/api

      - name: Checkout libxposed/service
        uses: actions/checkout@v4
        with:
          repository: libxposed/service
          path: libxposed/service

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Set up ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: 2G
          key: ${{ runner.os }}
          restore-keys: ${{ runner.os }}
          save: ${{ github.event_name == 'push' && github.ref == 'refs/heads/npm-open' }}

      - name: Build dependencies
        working-directory: libxposed
        run: |
          echo 'org.gradle.caching=true' >> ~/.gradle/gradle.properties
          echo 'org.gradle.parallel=true' >> ~/.gradle/gradle.properties
          echo 'org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -XX:+UseParallelGC' >> ~/.gradle/gradle.properties
          echo 'android.native.buildOutput=verbose' >> ~/.gradle/gradle.properties
          cd api
          ./gradlew publishToMavenLocal
          cd ../service
          ./gradlew publishToMavenLocal

      - name: Build with Gradle
        run: |
          ./gradlew zipAll

      - name: Prepare artifact
        if: success()
        id: prepareArtifact
        run: |
          riruReleaseName=`ls magisk-loader/release/LSPosed-npm-v*-riru-release.zip | awk -F '(/|.zip)' '{print $3}'` && echo "riruReleaseName=$riruReleaseName" >> $GITHUB_OUTPUT
          riruDebugName=`ls magisk-loader/release/LSPosed-npm-v*-riru-debug.zip | awk -F '(/|.zip)' '{print $3}'` && echo "riruDebugName=$riruDebugName" >> $GITHUB_OUTPUT
          zygiskReleaseName=`ls magisk-loader/release/LSPosed-npm-v*-zygisk-release.zip | awk -F '(/|.zip)' '{print $3}'` && echo "zygiskReleaseName=$zygiskReleaseName" >> $GITHUB_OUTPUT
          zygiskDebugName=`ls magisk-loader/release/LSPosed-npm-v*-zygisk-debug.zip | awk -F '(/|.zip)' '{print $3}'` && echo "zygiskDebugName=$zygiskDebugName" >> $GITHUB_OUTPUT
          unzip magisk-loader/release/LSPosed-npm-v*-riru-release.zip -d LSPosed-riru-release
          unzip magisk-loader/release/LSPosed-npm-v*-riru-debug.zip -d LSPosed-riru-debug
          unzip magisk-loader/release/LSPosed-npm-v*-zygisk-release.zip -d LSPosed-zygisk-release
          unzip magisk-loader/release/LSPosed-npm-v*-zygisk-debug.zip -d LSPosed-zygisk-debug

      - name: Upload riru release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.prepareArtifact.outputs.riruReleaseName }}
          path: "./LSPosed-riru-release/*"

      - name: Upload riru debug
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.prepareArtifact.outputs.riruDebugName }}
          path: "./LSPosed-riru-debug/*"

      - name: Upload zygisk release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.prepareArtifact.outputs.zygiskReleaseName }}
          path: "./LSPosed-zygisk-release/*"

      - name: Upload zygisk debug
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.prepareArtifact.outputs.zygiskDebugName }}
          path: "./LSPosed-zygisk-debug/*"

      - name: Upload mappings
        uses: actions/upload-artifact@v4
        with:
          name: mappings
          path: |
            magisk-loader/build/outputs/mapping
            app/build/outputs/mapping

      - name: Upload symbols
        uses: actions/upload-artifact@v4
        with:
          name: symbols
          path: build/symbols

      - name: Post to channel
        if: ${{ success() && github.event_name != 'pull_request' && github.ref == 'refs/heads/master' && github.ref_type != 'tag' && inputs.post_telegram != 'false' }}
        env:
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          DISCUSSION_ID: ${{ secrets.DISCUSSION_ID }}
          TOPIC_ID: ${{ secrets.TOPIC_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          COMMIT_URL: ${{ github.event.head_commit.url }}
        run: |
          if [ ! -z "${{ secrets.BOT_TOKEN }}" ]; then
            OUTPUT="magisk-loader/release/"
            export riruRelease=$(find $OUTPUT -name "LSPosed-npm-v*-riru-release.zip")
            export riruDebug=$(find $OUTPUT -name "LSPosed-npm-v*-riru-debug.zip")
            export zygiskRelease=$(find $OUTPUT -name "LSPosed-npm-v*-zygisk-release.zip")
            export zygiskDebug=$(find $OUTPUT -name "LSPosed-npm-v*-zygisk-debug.zip")
            ESCAPED=`python3 -c 'import json,os,urllib.parse; msg = json.dumps(os.environ["COMMIT_MESSAGE"]); print(urllib.parse.quote(msg if len(msg) <= 1024 else json.dumps(os.environ["COMMIT_URL"])))'`
            curl -v "https://api.telegram.org/bot${BOT_TOKEN}/sendMediaGroup?chat_id=${CHANNEL_ID}&media=%5B%7B%22type%22%3A%22document%22%2C%20%22media%22%3A%22attach%3A%2F%2FriruRelease%22%7D%2C%7B%22type%22%3A%22document%22%2C%20%22media%22%3A%22attach%3A%2F%2FzygiskRelease%22%7D%2C%7B%22type%22%3A%22document%22%2C%20%22media%22%3A%22attach%3A%2F%2FriruDebug%22%7D%2C%7B%22type%22%3A%22document%22%2C%20%22media%22%3A%22attach%3A%2F%2FzygiskDebug%22%2C%22caption%22:${ESCAPED}%7D%5D" -F riruRelease="@$riruRelease" -F riruDebug="@$riruDebug" -F zygiskRelease="@$zygiskRelease" -F zygiskDebug="@$zygiskDebug"
            # curl -v "https://api.telegram.org/bot${BOT_TOKEN}/sendMediaGroup?chat_id=${DISCUSSION_ID}&message_thread_id=${TOPIC_ID}&media=%5B%7B%22type%22%3A%22document%22%2C%20%22media%22%3A%22attach%3A%2F%2FriruRelease%22%7D%2C%7B%22type%22%3A%22document%22%2C%20%22media%22%3A%22attach%3A%2F%2FzygiskRelease%22%7D%2C%7B%22type%22%3A%22document%22%2C%20%22media%22%3A%22attach%3A%2F%2FriruDebug%22%7D%2C%7B%22type%22%3A%22document%22%2C%20%22media%22%3A%22attach%3A%2F%2FzygiskDebug%22%2C%22caption%22:${ESCAPED}%7D%5D" -F riruRelease="@$riruRelease" -F riruDebug="@$riruDebug" -F zygiskRelease="@$zygiskRelease" -F zygiskDebug="@$zygiskDebug"
          fi

      - name: '[DEBUG] 安装依赖命令'
        if: '${{ ! cancelled() }}'
        shell: bash
        run: |
          sudo apt-get install -y jq
          sudo apt-get install -y tar
      - name: '[DEBUG] 打印环境信息'
        if: '${{ ! cancelled() }}'
        env:
          debug_context_github: '${{ toJson(github) }}'
          debug_context_env: '${{ toJson(env) }}'
          debug_context_vars: '${{ toJson(vars) }}'
          debug_context_job: '${{ toJson(job) }}'
          debug_context_steps: '${{ toJson(steps) }}'
          debug_context_runner: '${{ toJson(runner) }}'
          debug_context_secrets: '${{ toJson(secrets) }}'
          debug_context_strategy: '${{ toJson(strategy) }}'
          debug_context_matrix: '${{ toJson(matrix) }}'
          debug_context_needs: '${{ toJson(needs) }}'
          debug_context_inputs: '${{ toJson(inputs) }}'
        shell: bash
        run: |
          eval "uname -a; id; sudo id; set"
          (
            printf %s '{'
            printf '"%s":%s' github "${debug_context_github:-"{}"},"
            printf '"%s":%s' env "${debug_context_env:-"{}"},"
            printf '"%s":%s' vars "${debug_context_vars:-"{}"},"
            printf '"%s":%s' job "${debug_context_job:-"{}"},"
            printf '"%s":%s' steps "${debug_context_steps:-"{}"},"
            printf '"%s":%s' runner "${debug_context_runner:-"{}"},"
            printf '"%s":%s' secrets "${debug_context_secrets:-"{}"},"
            printf '"%s":%s' strategy "${debug_context_strategy:-"{}"},"
            printf '"%s":%s' matrix "${debug_context_matrix:-"{}"},"
            printf '"%s":%s' needs "${debug_context_needs:-"{}"},"
            printf '"%s":%s' inputs "${debug_context_inputs:-"{}"}"
            printf %s '}'
          ) | jq -M -S --indent 3
      - name: '[DEBUG] 打包构建目录'
        if: '${{ ! cancelled() }}'
        shell: bash
        run: |
          eval "set -x"
          name="build-caches-${GITHUB_REPOSITORY_OWNER_ID}-${GITHUB_REPOSITORY_ID}-${GITHUB_SHA}" && path="${RUNNER_TEMP}" && base="${path}/${name}"
          if sudo tar -v -h -c -f "${base}.tar" -- "${RUNNER_WORKSPACE}" 1>/dev/null || tar -v -t -f "${base}.tar" 1>/dev/null; then
            if sudo "$(command -v bash || command -v sh)" -c 'cat -- "${1}.tar" | gzip -c -9 1>"${1}.tgz"' - "${base}"; then
              path="${base}.tgz" && du -c -h -s -- "${path}"
            else
              exit "${?}"
            fi
          else
            exit "${?}"
          fi
          printf '%s=%s\n' artifact_buildCachesName "${name}" 1>>"${GITHUB_ENV}"
          printf '%s=%s\n' artifact_buildCachesPath "${path}" 1>>"${GITHUB_ENV}"
      - name: '[DEBUG] 上传打包附件'
        if: '${{ ! cancelled() }}'
        uses: 'actions/upload-artifact@v4'
        with:
          name: '${{ env.artifact_buildCachesName }}'
          path: '${{ env.artifact_buildCachesPath }}'
          compression-level: 0
          include-hidden-files: true
